from Trie import *
tree = Trie()

insert(tree, "Hola Pedro ¿Como estas hoy?")
insert(tree, "Señora vaca")
insert(tree, "señora vaca")
insert(tree, "Hola Pablo ¿Como estas hoy?")
insert(tree, "------")
insert(tree, "ávbcc")
insert(tree, "a")
insert(tree, "a")
insert(tree, "a")
insert(tree, "a")
insert(tree, "a")
insert(tree, "a")
print(tree)